# Generated by Django 6.0.6 on 2026-06-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_stars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
