# Generated by Django 6.0.6 on 2026-06-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
